# Generated by Django 5.2.16 on 2026-07-08 14:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("icv_search", "0001_initial"),
        ("icv_search", "0002_searchquerylog"),
        ("icv_search", "0003_searchqueryaggregate"),
        ("icv_search", "0004_merchandising"),
        ("icv_search", "0005_click_tracking"),
        ("icv_search", "0006_alter_searchindex_settings_help_text"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name (e.g. 'products').",
                        max_length=100,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups. Blank in single-tenant mode.",
                        max_length=100,
                    ),
                ),
                (
                    "engine_uid",
                    models.CharField(
                        editable=False,
                        help_text="Computed index name sent to the search engine.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "primary_key_field",
                    models.CharField(
                        default="id",
                        help_text="Document field used as the primary key in the search engine.",
                        max_length=100,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine settings: searchable_attributes, filterable_attributes, sortable_attributes, synonyms, stop_words, ranking_rules.",
                    ),
                ),
                (
                    "document_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cached document count, updated by refresh task.",
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(
                        default=False,
                        help_text="Whether current settings have been pushed to the engine.",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful settings sync.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Deactivated indexes are not queried or synced.",
                    ),
                ),
            ],
            options={
                "verbose_name": "search index",
                "verbose_name_plural": "search indexes",
                "ordering": ["name"],
                "unique_together": {("tenant_id", "name")},
            },
        ),
        migrations.CreateModel(
            name="IndexSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("settings_updated", "Settings Updated"),
                            ("deleted", "Deleted"),
                            ("reindexed", "Reindexed"),
                            ("documents_added", "Documents Added"),
                            ("documents_deleted", "Documents Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, help_text="Error messages or sync metadata."),
                ),
                (
                    "task_uid",
                    models.CharField(
                        blank=True,
                        help_text="Engine-side task ID for async operations.",
                        max_length=100,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="icv_search.searchindex",
                    ),
                ),
            ],
            options={
                "verbose_name": "index sync log",
                "verbose_name_plural": "index sync logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical search index name (e.g. 'products').",
                        max_length=200,
                        verbose_name="index name",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The search query string submitted by the user.",
                        max_length=500,
                        verbose_name="query",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filter parameters passed to the search engine.",
                        verbose_name="filters",
                    ),
                ),
                (
                    "sort",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sort parameters passed to the search engine.",
                        verbose_name="sort",
                    ),
                ),
                (
                    "hit_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of results returned by the engine.",
                        verbose_name="hit count",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken by the search engine to process the query.",
                        verbose_name="processing time (ms)",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "is_zero_result",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when the query returned no hits.",
                        verbose_name="zero result",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context such as source page, session ID, or A/B test variant.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user who made the query, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_query_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "search query log",
                "verbose_name_plural": "search query logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["index_name", "is_zero_result"],
                        name="icv_search__index_n_08e7ef_idx",
                    ),
                    models.Index(
                        fields=["index_name", "tenant_id", "created_at"],
                        name="icv_search__index_n_09bc9e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchQueryAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical search index name (e.g. 'products').",
                        max_length=200,
                        verbose_name="index name",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="Normalised (lowercased) search query string.",
                        max_length=500,
                        verbose_name="query",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Calendar date on which these queries were made.",
                        verbose_name="date",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times this query was executed on this date.",
                        verbose_name="total count",
                    ),
                ),
                (
                    "zero_result_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of executions that returned no hits.",
                        verbose_name="zero result count",
                    ),
                ),
                (
                    "total_processing_time_ms",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Sum of all per-query processing times for this aggregate row.",
                        verbose_name="total processing time (ms)",
                    ),
                ),
            ],
            options={
                "verbose_name": "search query aggregate",
                "verbose_name_plural": "search query aggregates",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index_name", "query", "date", "tenant_id"),
                        name="icv_search_agg_unique",
                    )
                ],
                "indexes": [
                    models.Index(fields=["index_name", "date"], name="icv_srch_agg_idx_dt"),
                    models.Index(
                        fields=["index_name", "tenant_id", "date"],
                        name="icv_srch_agg_tnt_dt",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BoostRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "field",
                    models.CharField(help_text="Document field to evaluate.", max_length=200),
                ),
                (
                    "field_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Value to compare against. Ignored for 'exists' operator.",
                        max_length=500,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not equals"),
                            ("gt", "Greater than"),
                            ("gte", "Greater than or equal"),
                            ("lt", "Less than"),
                            ("lte", "Less than or equal"),
                            ("contains", "Contains"),
                            ("exists", "Field exists"),
                        ],
                        default="eq",
                        help_text="Comparison operator.",
                        max_length=20,
                    ),
                ),
                (
                    "boost_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Multiplicative weight. Values > 1 promote, values between 0 and 1 demote. Applied to the document's ranking score.",
                        max_digits=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "boost rule",
                "verbose_name_plural": "boost rules",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryRedirect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(help_text="URL to redirect the user to.", max_length=2000),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[
                            ("url", "External URL"),
                            ("category", "Category page"),
                            ("product", "Product page"),
                            ("page", "CMS page"),
                        ],
                        default="url",
                        help_text="Type of destination for analytics tracking.",
                        max_length=20,
                    ),
                ),
                (
                    "preserve_query",
                    models.BooleanField(
                        default=False,
                        help_text="Append the original query as a ?q= parameter to the destination URL.",
                    ),
                ),
                (
                    "http_status",
                    models.IntegerField(
                        choices=[(301, "301 Permanent"), (302, "302 Temporary")],
                        default=302,
                        help_text="HTTP status code for the redirect response.",
                    ),
                ),
            ],
            options={
                "verbose_name": "query redirect",
                "verbose_name_plural": "query redirects",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryRewrite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "rewritten_query",
                    models.CharField(
                        help_text="The query string to use instead of the original.",
                        max_length=500,
                    ),
                ),
                (
                    "apply_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional filters to inject into the search request.",
                    ),
                ),
                (
                    "apply_sort",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sort order to inject into the search request.",
                    ),
                ),
                (
                    "merge_filters",
                    models.BooleanField(
                        default=True,
                        help_text="Merge injected filters with existing filters. When False, replaces them.",
                    ),
                ),
            ],
            options={
                "verbose_name": "query rewrite",
                "verbose_name_plural": "query rewrites",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Banner headline.", max_length=200),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Banner body content (supports HTML).",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional banner image URL.",
                        max_length=2000,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional click-through URL.",
                        max_length=2000,
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Call-to-action text for the link.",
                        max_length=200,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Top of results"),
                            ("inline", "Inline within results"),
                            ("bottom", "Bottom of results"),
                            ("sidebar", "Sidebar"),
                        ],
                        default="top",
                        help_text="Where to display the banner relative to results.",
                        max_length=20,
                    ),
                ),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("informational", "Informational"),
                            ("promotional", "Promotional"),
                            ("warning", "Warning"),
                        ],
                        default="informational",
                        help_text="Semantic type of the banner for styling.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata for custom rendering logic.",
                    ),
                ),
            ],
            options={
                "verbose_name": "search banner",
                "verbose_name_plural": "search banners",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchPin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(help_text="ID of the document to pin.", max_length=255),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Zero-based position in results. Use -1 to bury (push to end).",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional label for the pin (e.g. 'sponsored', 'editorial pick').",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "search pin",
                "verbose_name_plural": "search pins",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZeroResultFallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical index name this rule applies to.",
                        max_length=200,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier. Blank applies to all tenants.",
                        max_length=200,
                    ),
                ),
                (
                    "query_pattern",
                    models.CharField(
                        help_text="Query pattern to match against incoming search queries.",
                        max_length=500,
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts with"),
                            ("regex", "Regular expression"),
                        ],
                        default="exact",
                        help_text="How query_pattern is compared to the search query.",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive rules are never evaluated.",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher priority rules are evaluated first.",
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active from this date/time. Blank means no start constraint.",
                        null=True,
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Rule is active until this date/time. Blank means no end constraint.",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this rule has been triggered.",
                    ),
                ),
                (
                    "fallback_type",
                    models.CharField(
                        choices=[
                            ("redirect", "Redirect to URL"),
                            ("alternative_query", "Run alternative query"),
                            ("curated_results", "Show curated document IDs"),
                            ("popular_in_category", "Show popular items in category"),
                        ],
                        help_text="Strategy to use when the original query returns zero results.",
                        max_length=30,
                    ),
                ),
                (
                    "fallback_value",
                    models.CharField(
                        help_text="Meaning depends on fallback_type: URL for redirect, query string for alternative_query, comma-separated IDs for curated_results, category identifier for popular_in_category.",
                        max_length=2000,
                    ),
                ),
                (
                    "fallback_filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional filters applied when executing the fallback search.",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of fallback attempts before giving up.",
                    ),
                ),
            ],
            options={
                "verbose_name": "zero-result fallback",
                "verbose_name_plural": "zero-result fallbacks",
                "ordering": ["-priority", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="searchpin",
            constraint=models.UniqueConstraint(
                fields=("index_name", "tenant_id", "query_pattern", "document_id"),
                name="icv_search_pin_unique",
            ),
        ),
        migrations.CreateModel(
            name="SearchClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical search index name (e.g. 'products').",
                        max_length=200,
                        verbose_name="index name",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="The search query string that produced the result page.",
                        max_length=500,
                        verbose_name="query",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier of the document that was clicked.",
                        max_length=500,
                        verbose_name="document ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Zero-based position of the clicked document in the result list.",
                        verbose_name="position",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra context such as source page, session ID, or A/B test variant.",
                        verbose_name="metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "search click",
                "verbose_name_plural": "search clicks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["index_name", "query", "created_at"],
                        name="icv_srch_clk_qry_dt",
                    ),
                    models.Index(fields=["index_name", "document_id"], name="icv_srch_clk_doc"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchClickAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "index_name",
                    models.CharField(
                        db_index=True,
                        help_text="Logical search index name (e.g. 'products').",
                        max_length=200,
                        verbose_name="index name",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="Normalised (lowercased) search query string.",
                        max_length=500,
                        verbose_name="query",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        db_index=True,
                        help_text="Identifier of the document that was clicked.",
                        max_length=500,
                        verbose_name="document ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Calendar date on which these clicks occurred.",
                        verbose_name="date",
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of clicks on this document for this query on this date.",
                        verbose_name="click count",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tenant identifier for multi-tenant setups.",
                        max_length=200,
                        verbose_name="tenant ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "search click aggregate",
                "verbose_name_plural": "search click aggregates",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "index_name",
                            "query",
                            "document_id",
                            "date",
                            "tenant_id",
                        ),
                        name="icv_search_click_agg_unique",
                    )
                ],
                "indexes": [
                    models.Index(
                        fields=["index_name", "query", "date"],
                        name="icv_srch_clkagg_qry_dt",
                    ),
                    models.Index(
                        fields=["index_name", "date", "tenant_id"],
                        name="icv_srch_clkagg_tnt_dt",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="searchindex",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Engine settings in the search engine's native camelCase form: searchableAttributes, filterableAttributes, sortableAttributes, synonyms, stopWords, rankingRules.",
            ),
        ),
    ]
