# Generated by Django 6.1.1 on 2026-09-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("icv_search", "0001_squashed_0006_alter_searchindex_settings_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchclick",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Advisory tenant label. NOT an isolation boundary: it is a plain indexed string with no foreign key and no constraint, nothing validates it, and no manager filters on it. The service-layer click functions filter by it only when a caller passes a non-empty tenant_id, and they FAIL OPEN when it is omitted, returning every tenant's rows. A caller reaching these models directly is unscoped entirely. Treat it as a grouping label for reporting, never as a security control.",
                max_length=200,
                verbose_name="tenant ID",
            ),
        ),
        migrations.AlterField(
            model_name="searchquerylog",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Advisory tenant label. NOT an isolation boundary: it is a plain indexed string with no foreign key and no constraint, nothing validates it, and no manager filters on it. The service-layer analytics functions filter by it only when a caller passes a non-empty tenant_id, and they FAIL OPEN when it is omitted, returning every tenant's rows. A caller reaching these models directly is unscoped entirely. Treat it as a grouping label for reporting, never as a security control.",
                max_length=200,
                verbose_name="tenant ID",
            ),
        ),
    ]
